name: Deployment-of-a-python-app-in-parallel
on: [push]
jobs:
  build-and-deploy01:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This has been triggered by ${{ github.event_name }}"
      - run: echo "This First job is running on ${{ runner.os }}"
      - name: "Check out repository code(first)"
        uses: actions/checkout@v2
      - name: "Set up Python 3.9(first)"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install deps(first)"
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: "Lint with pylint(first)"
        run: |
          python lint_test.py
      - name: "Build container(first)"
        run: |
          echo "Builder container image...(first)"
          sleep 3
      - name: "Deploying to cluster...(first)"
        run: |
          echo "Deploying to cluster...(first)"
          sleep 2
          echo "Container deployed.(first)"
      - run: echo "This First job status is ${{ job.status }}"
  build-and-deploy02:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This has been triggered by ${{ github.event_name }}"
      - run: echo "This Second job is running on ${{ runner.os }}"
      - name: "Check out repository code(second)"
        uses: actions/checkout@v2
      - name: "Set up Python 3.9(second)"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install deps(second)"
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: "Lint with pylint(second)"
        run: |
          python lint_test.py
      - name: "Build container(second)"
        run: |
          echo "Builder container image..."
          sleep 3
      - name: "Deploying to cluster...(second)"
        run: |
          echo "Deploying to cluster...(second)"
          sleep 2
          echo "Container deployed.(second)"
      - run: echo "This Second job status is ${{ job.status }}"